#!/bin/bash

# list number of running jobs on AWS Batch

set -euo pipefail

. ~/.secrets

QUEUE="registry-512"

count=$(/usr/local/bin/aws \
  batch \
  list-jobs \
  --job-queue ${QUEUE} \
  | /usr/local/bin/jq ".jobSummaryList | length")

if [ ${count} -gt 0 ]; then
  echo "${count} ⚙"
fi
