#!/bin/bash

#
# Display how many ec2 instances are currently running.
#
# Austin G. Davis-Richardson <harekrishna@gmail.com>
#
# Requirements:
#
# - aws-cli
# - jq
#

set -euo pipefail

. ~/.secrets

total_instances=0
out=''

function describe_instances() {

  instance_details=$(/usr/local/bin/aws ec2 describe-instances --region ${region})

  count=$(
    echo ${instance_details} \
      | /usr/local/bin/jq '[.Reservations[] | .Instances[] | select(.State.Name  == "running")]  | length'
  )

  instances=$(
    echo ${instance_details} \
      | /usr/local/bin/jq '.Reservations[].Instances[] |  "" + .KeyName + ".[" + .InstanceType +  "]" + "(" + .State.Name + ")"' \
      | grep running
  )

  total_instances=$((total_instances+${count}))

  for instance in ${instances}; do
    line=$(echo ${instance} | tr -d '"')
    out="${out}\n${line}"
  done
}

for region in 'us-east-1' 'us-west-1'; do
  describe_instances
done

if [ ${total_instances} -gt 0 ]; then
  echo "${total_instances} 📡"
  echo '---'
  echo -e ${out}
fi
