#!/bin/bash

symbols=(
  MANA
  XRP
)

for symbol in "${symbols[@]}"; do
  price=$(
    curl --silent -L "https://binance.com/api/v1/ticker/24hr?symbol=${symbol}BTC" \
      | /usr/local/bin/jq .weightedAvgPrice \
      | tr -d '"'
  )

  m_price=$(echo "${price} * 1000" | bc)

  echo "${symbol}=${m_price} mBTC"
done
